#:schema node_modules/wrangler/config-schema.json
name = "loj"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"
[[d1_databases]]
binding = "DB"
database_name = "loj-db"
database_id = "" # 运行 `npx wrangler d1 create loj-db` 后填写